### PR TITLE
Fix routing for custom bottles

### LINKED ISSUE #211: Adding a custom app breaks eel's routes
**Eel version**
I am using eel 0.11.0 with python 3.8.

**Describe the bug**
When adding a own app, none of the routes that are required for eel to work are served anymore.

**To Reproduce**
Run the following code-snippet:
```python
app = bottle.Bottle()
eel.init('web', allowed_extensions=['.js', '.html'])

def onclose(page, sockets):
    pass

# This is not strictly neccesary to break eel, it even won't work without if.
@app.route('/<site>/')
def redirect_to_index(site):
    bottle.redirect('/{}/index.html'.format(site))

eel.start(
    close_callback=onclose,
    app=app)
```

**Expected behavior**
Even when specifying a custom app, bottle should still serve eel's own routes.

**Additional context**
This is related to the changes introduced in #203

### PR DESCRIPTION
**Pull request by samuelhwilliams**
PR #203 added the ability for users to pass a custom Bottle instance to
Eel, which was intended to help them add middleware. Unfortunately, the
custom app instance has no routing set up and so fundamentally fails to
support Eel's functionality.

This patch applies the functions that handle routing to any custom
bottles before handing off off to bottle to run the server.

Fix #211

### CODE REVIEW

File: eel/__init__.py [hunk 1]
```diff
@@ -138,12 +138,18 @@ def run_lambda():
             HOST = '0.0.0.0'
         else:
             HOST = _start_args['host']
+
+        app = _start_args.get('app', btl.default_app)  # type: btl.Bottle
```
Comment (n0emis) [inline eel/__init__.py]: Scince this field is already present, because it got set in line 43.
This line has to be `app = _start_args['app']` and line 43 `'app': btl.default_app(), `
the app will crash if run without an set app, because `'NoneType' object has no attribute 'route`.

Comment (samuelhwilliams) [reply eel/__init__.py]: Gppd catch 👌
